add vars and refactor deploy code

diff --git a/.github/workflows/update_host.yml b/.github/workflows/update_host.yml
--- a/.github/workflows/update_host.yml
+++ b/.github/workflows/update_host.yml
@@ -108,7 +108,7 @@ jobs:
           merge_backup(){
             local ret=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$1"`
             if echo "$ret"|grep error; then
-              echo $ret;
+              echo "$ret"|grep 'namespace not found' && exit 1
             elif [ ! -z "$ret" ] && [ "$ret" != "[]" ]; then
               echo "get-data $1" >> $GITHUB_STEP_SUMMARY
               #curl -X PUT -H "Authorization:Bearer $CF_API_TOKEN" \
diff --git a/.github/workflows/update_ip.yml b/.github/workflows/update_ip.yml
--- a/.github/workflows/update_ip.yml
+++ b/.github/workflows/update_ip.yml
@@ -62,7 +62,7 @@ jobs:
           for key in $PROXYS_BAK $PROXYS; do
             ret=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$key"`
             if echo "$ret"|grep error; then
-              echo $ret
+              echo "$ret"|grep 'namespace not found' && exit 1
             elif [ ! -z "$ret" ] && ! echo "$ret"|grep '443":[]' ]; then
               echo "$ret" |tr -d '{"[]}'|sed -r 's/, ?/\n/g'|sed -r '/^\w*:$/d'|sed -r 's/^\w*:([\d\.]*)/\1/' >> ip.txt
               if [ $key == $PROXYS ]; then
